
<h1 style="color:#ffc0cb;font-size:70px;font-family:Georgia;text-align:center;"><strong>National Leagues 2017-2018</strong></h1>

In [16]:
# Install a conda package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install missingno


# work with data in tabular representation
from datetime import time
import pandas as pd
# round the data in the correlation matrix
import numpy as np
import os


# Modules for data visualization
import seaborn as sns
import missingno as msno

# run a python file 
%run ../../src/cleaning/function.py

# ignore DeprecationWarning Error Messages
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: missingno in c:\users\thu\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: scipy in c:\users\thu\anaconda3\lib\site-packages (from missingno) (1.7.1)
Requirement already satisfied: seaborn in c:\users\thu\anaconda3\lib\site-packages (from missingno) (0.11.2)
Requirement already satisfied: matplotlib in c:\users\thu\anaconda3\lib\site-packages (from missingno) (3.4.3)
Requirement already satisfied: numpy in c:\users\thu\anaconda3\lib\site-packages (from missingno) (1.20.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (3.0.4)
Requirement already satisfied: six in c:\users\thu\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->missingno) (1.16.0)
Requirement already satisfied: pandas>=0.23 in c:\users\thu\anaconda3\lib\site-packages (from seaborn->missingno) (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\thu\anaconda3\lib\site-packages (from pandas>=0.23->seaborn->missingno) (2021.3)

<a id="1.2"></a>
# Data Retrieving
***
In order to load data properly, the data in csv file have to be examined carefully. First of all, all the categories are seperated by the "," and strip the extra-whitespaces at the begin by setting "skipinitialspace = True".

In [3]:
# set the path of the external data from the third party source
external_data_path = os.path.join(os.path.pardir, '', '..', 'data','external', 'National Leagues', 'Season 2017-2018')

# get each specfic file
english_premier_league_df = os.path.join(external_data_path, 'E0_English Premier League_2017-2018.csv')
efl_championship_df = os.path.join(external_data_path, 'E1_EFL Championship_2017-2018.csv')
efl_league_one_df = os.path.join(external_data_path, 'E2_EFL League One_2017-2018.csv')
efl_league_two_df = os.path.join(external_data_path, 'E3_EFL League Two_2017-2018.csv')

# import dataset
english_premier_league_df = pd.read_csv(english_premier_league_df, delimiter=',', skipinitialspace = True)
efl_championship_df = pd.read_csv(efl_championship_df, delimiter=',', skipinitialspace = True)
efl_league_one_df = pd.read_csv(efl_league_one_df, delimiter=',', skipinitialspace = True)
efl_league_two_df = pd.read_csv(efl_league_two_df, delimiter=',', skipinitialspace = True)

# print out the shape
print("The shape of the E0_English Premier League 2017-2018 dataframe is (row, column):", str(english_premier_league_df.shape))
print("The shape of the E1_EFL Championship 2017-2018 dataframe is (row, column):", str(efl_championship_df.shape))
print("The shape of the E2_EFL League One 2017-2018 dataframe is (row, column):", str(efl_league_one_df.shape))
print("The shape of the E3_EFL League Two 2017-2018 dataframe is (row, column):", str(efl_league_two_df.shape), "\n\n")

The shape of the E0_English Premier League 2017-2018 dataframe is (row, column): (380, 65)
The shape of the E1_EFL Championship 2017-2018 dataframe is (row, column): (552, 65)
The shape of the E2_EFL League One 2017-2018 dataframe is (row, column): (552, 65)
The shape of the E3_EFL League Two 2017-2018 dataframe is (row, column): (552, 65)

In [4]:
print(profile_summary(english_premier_league_df, plot=False))
style(english_premier_league_df.head(3))

Profiling datasets
   Attribute     Type  Num. Missing Values  Num. Unique Values Sknewness   Kurtosis
0       FTHG    int64                  0.0                 7.0  0.956765    0.64754
1       FTAG    int64                  0.0                 7.0   1.04195   0.730415
2       HTHG    int64                  0.0                 5.0  1.230172    1.25054
3       HTAG    int64                  0.0                 4.0  1.392669   1.280836
4         HS    int64                  0.0                32.0  0.612015    0.22362
5         AS    int64                  0.0                28.0   0.57166   0.432377
6        HST    int64                  0.0                15.0  0.822497   0.504766
7        AST    int64                  0.0                13.0  0.644081   0.397813
8         HF    int64                  0.0                18.0  0.227368  -0.232851
9         AF    int64                  0.0                20.0  0.634971   1.286039
10        HC    int64                  0.0                17.0  0.624791   0.398201
11        AC    int64                  0.0                14.0  0.616295   0.099451
12        HY    int64                  0.0                 7.0  0.845808   0.526293
13        AY    int64                  0.0                 8.0  0.787123    0.59945
14        HR    int64                  0.0                 3.0  5.134633  27.963732
15        AR    int64                  0.0                 2.0  3.786051   12.33418
16     B365H  float64                  0.0               100.0  2.348481     5.9089
17     B365D  float64                  0.0                41.0  1.984226   4.238112
18     B365A  float64                  0.0                96.0  2.052854    4.28547
19       BWH  float64                  0.0                98.0  2.228939   5.207885
20       BWD  float64                  0.0                43.0  1.911071   4.017059
21       BWA  float64                  0.0               106.0  1.957727   3.761638
22       IWH  float64                  0.0                71.0  2.125564   5.304855
23       IWD  float64                  0.0                33.0  1.640859   2.159046
24       IWA  float64                  0.0                72.0  1.882701   3.001316
25       LBH  float64                  0.0                92.0  2.495004   7.032466
26       LBD  float64                  0.0                37.0  2.190038   6.041948
27       LBA  float64                  0.0                89.0  2.112398   4.250899
28       PSH  float64                  0.0               237.0  2.253768   5.070315
29       PSD  float64                  0.0               219.0  2.089699   5.282003
30       PSA  float64                  0.0               271.0  1.844354   2.725407
31       WHH  float64                  0.0                73.0  2.340975   5.976497
32       WHD  float64                  0.0                28.0  1.882867   3.616713
33       WHA  float64                  0.0                72.0  1.982693   3.553762
34       VCH  float64                  0.0                87.0   2.41049   6.455101
35       VCD  float64                  0.0                43.0  2.046171   4.822883
36       VCA  float64                  0.0                91.0  1.861983   2.724848
37     Bb1X2    int64                  0.0                12.0  0.451567  -0.961679
38     BbMxH  float64                  0.0               183.0  2.432846   6.519821
39     BbAvH  float64                  0.0               228.0  2.287564   5.569706
40     BbMxD  float64                  0.0               146.0  2.102426   5.116993
41     BbAvD  float64                  0.0               205.0  1.898192    3.87116
42     BbMxA  float64                  0.0               184.0  2.059234   3.875254
43     BbAvA  float64                  0.0               282.0   1.91455   3.252559
44      BbOU    int64                  0.0                17.0  0.188135  -0.414177
45  BbMx>2.5  float64                  0.0               130.0  0.388195  -0.511164
46  BbAv>2.5  float64                  0.0               126.0  0.311473  -0.662852
47  BbMx<2.5  float64                  0.0               122.0  1.365691   2.425944
48  BbAv<2.5  float64                  0.0               139.0  1.240807   1.934868
49      BbAH    int64                  0.0                11.0 -0.440695   0.339977
50     BbAHh  float64                  0.0                20.0 -0.095524  -0.246789
51   BbMxAHH  float64                  0.0                69.0  0.383675  -0.014606
52   BbAvAHH  float64                  0.0                66.0   0.30676  -0.117467
53   BbMxAHA  float64                  0.0                67.0  0.396035   0.071036
54   BbAvAHA  float64                  0.0                66.0  0.307095   0.035503
55      PSCH  float64                  0.0               234.0  2.243312    5.34369
56      PSCD  float64                  0.0               199.0  2.303703   6.683765
57      PSCA  float64                  0.0               267.0  1.940747   3.343466
58       Div   object                  0.0                 1.0       N/A        N/A
59      Date   object                  0.0               105.0       N/A        N/A
60  HomeTeam   object                  0.0                20.0       N/A        N/A
61  AwayTeam   object                  0.0                20.0       N/A        N/A
62       FTR   object                  0.0                 3.0       N/A        N/A
63       HTR   object                  0.0                 3.0       N/A        N/A
64   Referee   object                  0.0                20.0       N/A        N/A
None

In [5]:
print(profile_summary(efl_championship_df, plot=False))
style(efl_championship_df.head(3))

Profiling datasets
   Attribute     Type  Num. Missing Values  Num. Unique Values           Sknewness   Kurtosis
0       FTHG    int64                  0.0                 7.0            0.816751   0.540014
1       FTAG    int64                  0.0                 6.0            0.921631   0.499114
2       HTHG    int64                  0.0                 5.0            1.105296   0.688968
3       HTAG    int64                  0.0                 4.0            1.363707   1.308818
4         HS    int64                  0.0                28.0            0.402636   0.347507
5         AS    int64                  0.0                27.0            0.587791   0.882432
6        HST    int64                  0.0                16.0             0.74639   1.237247
7        AST    int64                  0.0                12.0            0.599102   0.249741
8         HF    int64                  0.0                20.0            0.206297  -0.081271
9         AF    int64                  0.0                22.0            0.420622   0.147072
10        HC    int64                  0.0                16.0             0.59989   0.217049
11        AC    int64                  0.0                16.0            0.729281   0.713947
12        HY    int64                  0.0                 7.0            0.546873   0.016311
13        AY    int64                  0.0                 7.0            0.406196  -0.389316
14        HR    int64                  0.0                 3.0            4.346205  18.980742
15        AR    int64                  0.0                 3.0            3.113132   9.095503
16     B365H  float64                  0.0                84.0            1.318249   2.154739
17     B365D  float64                  0.0                28.0            4.038111  29.630211
18     B365A  float64                  0.0                80.0            2.231899   8.243184
19       BWH  float64                  0.0                69.0             1.30344   2.146567
20       BWD  float64                  0.0                24.0            3.693877  25.329298
21       BWA  float64                  0.0                71.0            1.811001   5.446567
22       IWH  float64                  0.0                87.0            1.259622   1.888905
23       IWD  float64                  0.0                41.0            2.658205  12.976744
24       IWA  float64                  0.0               107.0            1.742206   5.038795
25       LBH  float64                  0.0                69.0            1.301098   2.120978
26       LBD  float64                  0.0                25.0            2.917619  16.291858
27       LBA  float64                  0.0                71.0             2.13944   7.610947
28       PSH  float64                  0.0               225.0            1.399613   2.568738
29       PSD  float64                  0.0               139.0            3.328081  21.037884
30       PSA  float64                  0.0               329.0            2.140759   7.388561
31       WHH  float64                  1.0                60.0  1.3407945909843144   2.530824
32       WHD  float64                  1.0                20.0  2.4293484149348057   8.997213
33       WHA  float64                  1.0                58.0  1.6900764174917005   3.675223
34       VCH  float64                  0.0                74.0            1.359745   2.435088
35       VCD  float64                  0.0                28.0            3.558669  22.817361
36       VCA  float64                  0.0                71.0              2.1843    7.62759
37     Bb1X2    int64                  0.0                11.0            0.118366  -1.380287
38     BbMxH  float64                  0.0               171.0            1.355149   2.346269
39     BbAvH  float64                  0.0               228.0            1.262754    2.00102
40     BbMxD  float64                  0.0               108.0            3.743889  26.222148
41     BbAvD  float64                  0.0               120.0            3.365057  21.015445
42     BbMxA  float64                  0.0               210.0            2.239783   8.148976
43     BbAvA  float64                  0.0               322.0            1.937586   6.028174
44      BbOU    int64                  0.0                16.0            0.008284  -0.647302
45  BbMx>2.5  float64                  0.0                99.0            -0.15768  -0.356516
46  BbAv>2.5  float64                  0.0                93.0           -0.177984  -0.434389
47  BbMx<2.5  float64                  0.0                91.0            1.186867   1.978756
48  BbAv<2.5  float64                  0.0                91.0            1.222001   2.096687
49      BbAH    int64                  0.0                12.0           -0.336059   0.389765
50     BbAHh  float64                  0.0                13.0           -0.247637   0.310284
51   BbMxAHH  float64                  0.0                70.0            0.453455   0.318572
52   BbAvAHH  float64                  0.0                65.0            0.317855   0.151576
53   BbMxAHA  float64                  0.0                64.0            0.296997   0.092458
54   BbAvAHA  float64                  0.0                64.0            0.164646  -0.086523
55      PSCH  float64                  0.0               239.0            1.499657   3.046766
56      PSCD  float64                  0.0               146.0            3.079498  17.534867
57      PSCA  float64                  0.0               349.0            2.215646   7.916168
58       Div   object                  0.0                 1.0                 N/A        N/A
59      Date   object                  0.0               105.0                 N/A        N/A
60  HomeTeam   object                  0.0                24.0                 N/A        N/A
61  AwayTeam   object                  0.0                24.0                 N/A        N/A
62       FTR   object                  0.0                 3.0                 N/A        N/A
63       HTR   object                  0.0                 3.0                 N/A        N/A
64   Referee   object                  0.0                35.0                 N/A        N/A
None

In [6]:
print(profile_summary(efl_league_one_df, plot=False))
style(efl_league_one_df.head(3))

Profiling datasets
   Attribute     Type  Num. Missing Values  Num. Unique Values Sknewness   Kurtosis
0       FTHG    int64                  0.0                 6.0  0.714063   0.186521
1       FTAG    int64                  0.0                 7.0  1.075392   1.656333
2       HTHG    int64                  0.0                 5.0  1.302611   1.837388
3       HTAG    int64                  0.0                 4.0  1.285127   1.017124
4         HS    int64                  0.0                28.0  0.446916   0.213233
5         AS    int64                  0.0                25.0  0.759023   1.102136
6        HST    int64                  0.0                15.0  0.555683   0.379305
7        AST    int64                  0.0                15.0  0.975898   2.067356
8         HF    int64                  0.0                22.0   0.30673     0.0049
9         AF    int64                  0.0                24.0  0.284674  -0.105135
10        HC    int64                  0.0                18.0  0.757263    0.85044
11        AC    int64                  0.0                15.0  0.615407   0.351519
12        HY    int64                  0.0                 6.0  0.732704  -0.001509
13        AY    int64                  0.0                 7.0  0.572621   0.041202
14        HR    int64                  0.0                 3.0  3.583179  12.143487
15        AR    int64                  0.0                 3.0  3.355397  10.373195
16     B365H  float64                  0.0                86.0  2.663151  11.812218
17     B365D  float64                  0.0                25.0  2.402381   7.605979
18     B365A  float64                  0.0                81.0  2.025643   6.033613
19       BWH  float64                  0.0                74.0  2.191134   7.449716
20       BWD  float64                  0.0                23.0   2.46299   7.902689
21       BWA  float64                  0.0                73.0  1.737549   4.076788
22       IWH  float64                  0.0                86.0  2.193689   7.735312
23       IWD  float64                  0.0                36.0  2.085184    6.01104
24       IWA  float64                  0.0               102.0  1.658842   4.183536
25       LBH  float64                  0.0                72.0  2.449003   9.848414
26       LBD  float64                  0.0                22.0  2.142274   6.503621
27       LBA  float64                  0.0                72.0  2.224543   7.877675
28       PSH  float64                  0.0               224.0  2.589914  10.841511
29       PSD  float64                  0.0               126.0  2.380327   8.372339
30       PSA  float64                  0.0               303.0  2.202841   7.309291
31       WHH  float64                  0.0                60.0  2.418991   9.704114
32       WHD  float64                  0.0                18.0  2.186568   6.675637
33       WHA  float64                  0.0                63.0  1.972225   5.513758
34       VCH  float64                  0.0                71.0  2.542222  10.571335
35       VCD  float64                  0.0                25.0  2.373953   7.592334
36       VCA  float64                  0.0                73.0  2.133281   7.348868
37     Bb1X2    int64                  0.0                12.0   0.13361  -0.970307
38     BbMxH  float64                  0.0               187.0  2.676322  11.666452
39     BbAvH  float64                  0.0               216.0  2.386338   9.371119
40     BbMxD  float64                  0.0               100.0   2.48749   8.594909
41     BbAvD  float64                  0.0               115.0  2.444457   8.114062
42     BbMxA  float64                  0.0               217.0   2.12458   6.686362
43     BbAvA  float64                  0.0               297.0  1.949376   5.648067
44      BbOU    int64                  0.0                16.0 -0.063358  -0.434939
45  BbMx>2.5  float64                  0.0                88.0  0.677204   1.528335
46  BbAv>2.5  float64                  0.0                87.0  0.554038   0.847786
47  BbMx<2.5  float64                  0.0                82.0  0.423082   0.126288
48  BbAv<2.5  float64                  0.0                76.0  0.394908   0.002048
49      BbAH    int64                  0.0                13.0 -0.481394  -0.017397
50     BbAHh  float64                  0.0                12.0  0.083515   0.605242
51   BbMxAHH  float64                  0.0                65.0   0.30689   0.021283
52   BbAvAHH  float64                  0.0                59.0  0.211371  -0.195069
53   BbMxAHA  float64                  0.0                58.0  0.218603  -0.101558
54   BbAvAHA  float64                  0.0                58.0  0.174178  -0.229271
55      PSCH  float64                  0.0               220.0  2.554666   9.727918
56      PSCD  float64                  0.0               147.0   2.38991   9.199931
57      PSCA  float64                  0.0               305.0  2.215614   7.403875
58       Div   object                  0.0                 1.0       N/A        N/A
59      Date   object                  0.0                86.0       N/A        N/A
60  HomeTeam   object                  0.0                24.0       N/A        N/A
61  AwayTeam   object                  0.0                24.0       N/A        N/A
62       FTR   object                  0.0                 3.0       N/A        N/A
63       HTR   object                  0.0                 3.0       N/A        N/A
64   Referee   object                  0.0                61.0       N/A        N/A
None

In [7]:
print(profile_summary(efl_league_two_df, plot=False))
style(efl_league_two_df.head(3))

Profiling datasets
   Attribute     Type  Num. Missing Values  Num. Unique Values           Sknewness   Kurtosis
0       FTHG    int64                  0.0                 8.0            1.013816   1.756337
1       FTAG    int64                  0.0                 7.0            1.099224   1.505785
2       HTHG    int64                  0.0                 6.0            1.264279   2.137946
3       HTAG    int64                  0.0                 5.0            1.723111   3.084922
4         HS    int64                  0.0                26.0            0.579258   0.493021
5         AS    int64                  0.0                25.0            0.751631   1.310596
6        HST    int64                  0.0                13.0            0.540784   0.133366
7        AST    int64                  0.0                13.0            0.824421   1.338977
8         HF    int64                  0.0                21.0            0.345894   0.008275
9         AF    int64                  0.0                21.0            0.099717  -0.270043
10        HC    int64                  0.0                15.0            0.559383   0.084285
11        AC    int64                  0.0                15.0            0.635708   0.500125
12        HY    int64                  0.0                 7.0            0.717314   0.127904
13        AY    int64                  0.0                 7.0            0.744788   0.480129
14        HR    int64                  0.0                 3.0            3.561102  12.959843
15        AR    int64                  0.0                 3.0            3.571898  12.883112
16     B365H  float64                  0.0                79.0            1.389371   3.022354
17     B365D  float64                  0.0                26.0            1.527195   4.606351
18     B365A  float64                  0.0                78.0            1.257456   2.010511
19       BWH  float64                  0.0                67.0            1.308432   2.564546
20       BWD  float64                  0.0                21.0            1.456539   4.887993
21       BWA  float64                  0.0                65.0            1.218838   1.818363
22       IWH  float64                  0.0                74.0            1.199668   2.048786
23       IWD  float64                  0.0                32.0            1.406026   4.657011
24       IWA  float64                  0.0                87.0            1.048829   1.126966
25       LBH  float64                  0.0                62.0            1.283782   2.619425
26       LBD  float64                  0.0                21.0            1.560461   5.118448
27       LBA  float64                  0.0                66.0             1.29211   2.027112
28       PSH  float64                  1.0               222.0  1.5163346335889054   3.775384
29       PSD  float64                  1.0               121.0  1.6822874917891464   4.840925
30       PSA  float64                  1.0               291.0  1.3204112039190494   2.166477
31       WHH  float64                  0.0                51.0            1.336307   2.920364
32       WHD  float64                  0.0                17.0            1.384203   4.344463
33       WHA  float64                  0.0                51.0            1.282725   2.060266
34       VCH  float64                  0.0                65.0            1.237767   2.327019
35       VCD  float64                  0.0                23.0            1.599542   4.998188
36       VCA  float64                  0.0                63.0            1.187307   1.551489
37     Bb1X2    int64                  0.0                12.0            0.171967  -1.018156
38     BbMxH  float64                  0.0               178.0            1.503915   3.640296
39     BbAvH  float64                  0.0               209.0            1.260204   2.461009
40     BbMxD  float64                  0.0                96.0            1.675637   5.458236
41     BbAvD  float64                  0.0               100.0            1.566249   5.315972
42     BbMxA  float64                  0.0               186.0            1.327819   2.136707
43     BbAvA  float64                  0.0               273.0            1.169265   1.529651
44      BbOU    int64                  0.0                15.0           -0.128317  -0.241307
45  BbMx>2.5  float64                  0.0                80.0            0.310422   0.323818
46  BbAv>2.5  float64                  0.0                76.0            0.257578   0.053975
47  BbMx<2.5  float64                  0.0                75.0            0.459417   0.126703
48  BbAv<2.5  float64                  0.0                72.0            0.448507  -0.017421
49      BbAH    int64                  0.0                13.0           -0.420231   0.125358
50     BbAHh  float64                  0.0                 9.0            0.120089   -0.09805
51   BbMxAHH  float64                  0.0                73.0            0.381517  -0.155163
52   BbAvAHH  float64                  0.0                69.0             0.32856  -0.204568
53   BbMxAHA  float64                  0.0                69.0            0.256257  -0.239182
54   BbAvAHA  float64                  0.0                63.0            0.219232  -0.250355
55      PSCH  float64                  0.0               221.0             1.78372   6.244108
56      PSCD  float64                  0.0               135.0            1.739432   5.659924
57      PSCA  float64                  0.0               282.0            1.354338   2.858589
58       Div   object                  0.0                 1.0                 N/A        N/A
59      Date   object                  0.0                70.0                 N/A        N/A
60  HomeTeam   object                  0.0                24.0                 N/A        N/A
61  AwayTeam   object                  0.0                24.0                 N/A        N/A
62       FTR   object                  0.0                 3.0                 N/A        N/A
63       HTR   object                  0.0                 3.0                 N/A        N/A
64   Referee   object                  0.0                57.0                 N/A        N/A
None

<a id="1.3"></a>
# [Rename columns base on their abbreviations](http://www.football-data.co.uk/notes.txt)
***
Since these columns are not in SQL naming convention will be more straightforward in later process. We will also analyse the column meaning

In [8]:
print(f'The list of E0_English Premier League 2017-2018 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

The list of E0_English Premier League 2017-2018 columns' names is: ['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA']

In [9]:
rename_cols(english_premier_league_df)
rename_cols(efl_championship_df)
rename_cols(efl_league_one_df)
rename_cols(efl_league_two_df)

print(f'The list of E0 English Premier League 2017-2018 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

The list of E0 English Premier League 2017-2018 columns' names is: ['league_division', 'match_date', 'home_team', 'away_team', 'full_time_home_team_goals', 'full_time_away_team_goals', 'full_time_result', 'half_time_home_team_goals', 'half_time_away_team_goals', 'half_time_result', 'referee', 'home_shots', 'away_shots', 'home_shots_on_target', 'away_shots_on_target', 'home_fouls_committed', 'away_fouls_committed', 'home_corners', 'away_corners', 'home_yellow_cards', 'away_yellow_cards', 'home_red_cards', 'away_red_cards', 'bet365_home_win_odds', 'bet365_draw_odds', 'bet365_away_win_odds', 'bet&win_home_win_odds', 'bet&win_draw_odds', 'bet&win_away_win_odds', 'interwetten_home_win_odds', 'interwetten_draw_odds', 'interwetten_away_win_odds', 'ladbrokes_home_win_odds', 'ladbrokes_draw_odds', 'ladbrokes_away_win_odds', 'pinnacle_home_win_odds', 'pinnacle_draw_odds', 'pinnacle_away_win_odds', 'william_hill_home_win_odds', 'william_hill_draw_odds', 'william_hill_away_win_odds', 'vc_bet_home_win_odds', 'vc_bet_draw_odds', 'vc_bet_away_win_odds', 'no_betbrain_bookmakers_calculated_odds_averages_maximums', 'betbrain_maximum_home_win_odds', 'betbrain_average_home_win_odds', 'betbrain_maximum_draw_odds', 'betbrain_average_draw_win_odds', 'betbrain_maximum_away_win_odds', 'betbrain_average_away_win_odds', 'no_betbrain_bookmakers_calculated_over/under_2.5_goals_averages_maximums', 'betbrain_maximum_over_2.5_goals', 'betbrain_average_over_2.5_goals', 'betbrain_maximum_under_2.5_goals', 'betbrain_average_under_2.5_goals', 'no_betbrain_bookmakers_asian_handicap_averages_maximums', 'betbrain_size_handicap_home', 'betbrain_maximum_asian_handicap_home_odds', 'betbrain_average_asian_handicap_home_odds', 'betbrain_maximum_asian_handicap_away_odds', 'betbrain_average_asian_handicap_away_odds', 'PSCH', 'PSCD', 'PSCA']

# Drop unecessary columns

In [10]:
english_premier_league_df = english_premier_league_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_championship_df = efl_championship_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_league_one_df = efl_league_one_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_league_two_df = efl_league_two_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)

In [11]:
print(f'The list of E0 English Premier League 2016 2017 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

The list of E0 English Premier League 2016 2017 columns' names is: ['league_division', 'match_date', 'home_team', 'away_team', 'full_time_home_team_goals', 'full_time_away_team_goals', 'full_time_result', 'half_time_home_team_goals', 'half_time_away_team_goals', 'half_time_result', 'referee', 'home_shots', 'away_shots', 'home_shots_on_target', 'away_shots_on_target', 'home_fouls_committed', 'away_fouls_committed', 'home_corners', 'away_corners', 'home_yellow_cards', 'away_yellow_cards', 'home_red_cards', 'away_red_cards', 'bet365_home_win_odds', 'bet365_draw_odds', 'bet365_away_win_odds', 'bet&win_home_win_odds', 'bet&win_draw_odds', 'bet&win_away_win_odds', 'interwetten_home_win_odds', 'interwetten_draw_odds', 'interwetten_away_win_odds', 'ladbrokes_home_win_odds', 'ladbrokes_draw_odds', 'ladbrokes_away_win_odds', 'pinnacle_home_win_odds', 'pinnacle_draw_odds', 'pinnacle_away_win_odds', 'william_hill_home_win_odds', 'william_hill_draw_odds', 'william_hill_away_win_odds', 'vc_bet_home_win_odds', 'vc_bet_draw_odds', 'vc_bet_away_win_odds', 'no_betbrain_bookmakers_calculated_odds_averages_maximums', 'betbrain_maximum_home_win_odds', 'betbrain_average_home_win_odds', 'betbrain_maximum_draw_odds', 'betbrain_average_draw_win_odds', 'betbrain_maximum_away_win_odds', 'betbrain_average_away_win_odds', 'no_betbrain_bookmakers_calculated_over/under_2.5_goals_averages_maximums', 'betbrain_maximum_over_2.5_goals', 'betbrain_average_over_2.5_goals', 'betbrain_maximum_under_2.5_goals', 'betbrain_average_under_2.5_goals', 'no_betbrain_bookmakers_asian_handicap_averages_maximums', 'betbrain_size_handicap_home', 'betbrain_maximum_asian_handicap_home_odds', 'betbrain_average_asian_handicap_home_odds', 'betbrain_maximum_asian_handicap_away_odds', 'betbrain_average_asian_handicap_away_odds']

# Lower Case the content

In this section we will convert all the string value in the column to uppercase for further processing and keep all the string uniformly format. This will improve the analysis of the data, and also easier to perform any function related to the string.

In [12]:
# Cast all values inside the dataframe (except the columns' name) into upper case.
english_premier_league_df = english_premier_league_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_championship_df = efl_championship_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_league_one_df = efl_league_one_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_league_two_df = efl_league_two_df.applymap(lambda s: s.lower() if type(s) == str else s)

# Concat dataframes
Clear the existing index and reset it in the result by setting the ignore_index option to True.

In [13]:
df = pd.concat([english_premier_league_df, efl_championship_df, efl_league_one_df, efl_league_two_df], ignore_index=True)
df.head()

,league_division,match_date,home_team,away_team,full_time_home_team_goals,full_time_away_team_goals,full_time_result,half_time_home_team_goals,half_time_away_team_goals,half_time_result,referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_fouls_committed,away_fouls_committed,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,bet365_home_win_odds,bet365_draw_odds,bet365_away_win_odds,bet&win_home_win_odds,bet&win_draw_odds,bet&win_away_win_odds,interwetten_home_win_odds,interwetten_draw_odds,interwetten_away_win_odds,ladbrokes_home_win_odds,ladbrokes_draw_odds,ladbrokes_away_win_odds,pinnacle_home_win_odds,pinnacle_draw_odds,pinnacle_away_win_odds,william_hill_home_win_odds,william_hill_draw_odds,william_hill_away_win_odds,vc_bet_home_win_odds,vc_bet_draw_odds,vc_bet_away_win_odds,no_betbrain_bookmakers_calculated_odds_averages_maximums,betbrain_maximum_home_win_odds,betbrain_average_home_win_odds,betbrain_maximum_draw_odds,betbrain_average_draw_win_odds,betbrain_maximum_away_win_odds,betbrain_average_away_win_odds,no_betbrain_bookmakers_calculated_over/under_2.5_goals_averages_maximums,betbrain_maximum_over_2.5_goals,betbrain_average_over_2.5_goals,betbrain_maximum_under_2.5_goals,betbrain_average_under_2.5_goals,no_betbrain_bookmakers_asian_handicap_averages_maximums,betbrain_size_handicap_home,betbrain_maximum_asian_handicap_home_odds,betbrain_average_asian_handicap_home_odds,betbrain_maximum_asian_handicap_away_odds,betbrain_average_asian_handicap_away_odds
0,e0,11/08/2017,arsenal,leicester,4,3,h,2,2,d,m dean,27,6,10,3,9,12,9,4,0,1,0,0,1.53,4.5,6.50,1.50,4.60,6.75,1.47,4.5,6.50,1.44,4.40,6.50,1.53,4.55,6.85,1.53,4.2,6.00,1.53,4.50,6.50,41,1.55,1.51,4.60,4.43,6.89,6.44,37,1.65,1.61,2.43,2.32,21,-1.00,1.91,1.85,2.10,2.02
1,e0,12/08/2017,brighton,man city,0,2,a,0,0,d,m oliver,6,14,2,4,6,9,3,10,0,2,0,0,11.00,5.5,1.33,11.00,5.25,1.30,8.00,5.3,1.35,10.00,5.00,1.30,10.95,5.55,1.34,10.00,4.8,1.33,10.00,5.50,1.33,40,11.50,10.10,5.60,5.25,1.36,1.32,35,1.70,1.63,2.40,2.27,20,1.50,1.95,1.91,2.01,1.96
2,e0,12/08/2017,chelsea,burnley,2,3,a,0,3,a,c pawson,19,10,6,5,16,11,8,5,3,3,2,0,1.25,6.5,15.00,1.22,6.50,12.50,1.22,6.2,13.50,1.25,5.75,15.00,1.26,6.30,15.25,1.25,5.5,13.00,1.25,6.25,15.00,41,1.27,1.24,6.55,6.06,15.50,13.67,36,1.71,1.66,2.33,2.23,20,-1.75,2.03,1.97,1.95,1.90
3,e0,12/08/2017,crystal palace,huddersfield,0,3,a,0,2,a,j moss,14,8,4,6,7,19,12,9,1,3,0,0,1.83,3.6,5.00,1.80,3.50,4.75,1.85,3.5,4.30,1.80,3.40,4.60,1.83,3.58,5.11,1.80,3.3,5.00,1.83,3.60,5.00,41,1.86,1.81,3.65,3.50,5.11,4.82,36,2.19,2.11,1.79,1.72,18,-0.75,2.10,2.05,1.86,1.83
4,e0,12/08/2017,everton,stoke,1,0,h,1,0,h,n swarbrick,9,9,4,1,13,10,6,7,1,1,0,0,1.70,3.8,5.75,1.70,3.60,5.50,1.70,3.7,5.00,1.67,3.60,5.25,1.70,3.83,5.81,1.70,3.5,5.50,1.70,3.80,5.75,40,1.71,1.69,3.85,3.69,6.00,5.50,35,2.17,2.08,1.80,1.76,19,-0.75,1.94,1.90,2.01,1.98

<a id="3"></a>
<h1 style="color:#ffc0cb;font-size:40px;font-family:Georgia;text-align:center;"><strong>3. Save the Intermediate data that has been transformed</strong></h1>

In [17]:
write_interim_path(df, '2017-2018.csv', 'national_leagues')

cleaned 2017-2018.csv data was successfully saved!