
<h1 style="color:#ffc0cb;font-size:70px;font-family:Georgia;text-align:center;"><strong>National Leagues 2019-2020</strong></h1>

In [1]:
# Install a conda package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install missingno


# work with data in tabular representation
from datetime import time
import pandas as pd
# round the data in the correlation matrix
import numpy as np
import os


# Modules for data visualization
import seaborn as sns
import missingno as msno

# run a python file 
%run ../../src/cleaning/function.py

# ignore DeprecationWarning Error Messages
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: missingno in c:\users\thu\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: seaborn in c:\users\thu\anaconda3\lib\site-packages (from missingno) (0.11.2)
Requirement already satisfied: numpy in c:\users\thu\anaconda3\lib\site-packages (from missingno) (1.20.3)
Requirement already satisfied: scipy in c:\users\thu\anaconda3\lib\site-packages (from missingno) (1.7.1)
Requirement already satisfied: matplotlib in c:\users\thu\anaconda3\lib\site-packages (from missingno) (3.4.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\thu\anaconda3\lib\site-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: six in c:\users\thu\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->missingno) (1.16.0)
Requirement already satisfied: pandas>=0.23 in c:\users\thu\anaconda3\lib\site-packages (from seaborn->missingno) (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\thu\anaconda3\lib\site-packages (from pandas>=0.23->seaborn->missingno) (2021.3)

<a id="1.2"></a>
# Data Retrieving
***
In order to load data properly, the data in csv file have to be examined carefully. First of all, all the categories are seperated by the "," and strip the extra-whitespaces at the begin by setting "skipinitialspace = True".

In [2]:
# set the path of the external data from the third party source
external_data_path = os.path.join(os.path.pardir, '', '..', 'data','external', 'National Leagues', 'Season 2019-2020')

# get each specfic file
english_premier_league_df = os.path.join(external_data_path, 'E0_English Premier League_2019-2020.csv')
efl_championship_df = os.path.join(external_data_path, 'E1_EFL Championship_2019-2020.csv')
efl_league_one_df = os.path.join(external_data_path, 'E2_EFL League One_2019-2020.csv')
efl_league_two_df = os.path.join(external_data_path, 'E3_EFL League Two_2019-2020.csv')

# import dataset
english_premier_league_df = pd.read_csv(english_premier_league_df, delimiter=',', skipinitialspace = True)
efl_championship_df = pd.read_csv(efl_championship_df, delimiter=',', skipinitialspace = True)
efl_league_one_df = pd.read_csv(efl_league_one_df, delimiter=',', skipinitialspace = True)
efl_league_two_df = pd.read_csv(efl_league_two_df, delimiter=',', skipinitialspace = True)

# print out the shape
print("The shape of the E0_English Premier League 2019-2020 dataframe is (row, column):", str(english_premier_league_df.shape))
print("The shape of the E1_EFL Championship 2019-2020 dataframe is (row, column):", str(efl_championship_df.shape))
print("The shape of the E2_EFL League One 2019-2020 dataframe is (row, column):", str(efl_league_one_df.shape))
print("The shape of the E3_EFL League Two 2019-2020 dataframe is (row, column):", str(efl_league_two_df.shape), "\n\n")

The shape of the E0_English Premier League 2019-2020 dataframe is (row, column): (380, 106)
The shape of the E1_EFL Championship 2019-2020 dataframe is (row, column): (552, 106)
The shape of the E2_EFL League One 2019-2020 dataframe is (row, column): (400, 106)
The shape of the E3_EFL League Two 2019-2020 dataframe is (row, column): (440, 106)

In [3]:
style(english_premier_league_df.head(3))

In [4]:
style(efl_championship_df.head(3))

In [5]:
style(efl_league_one_df.head(3))

In [6]:
style(efl_league_two_df.head(3))

<a id="1.3"></a>
# [Rename columns base on their abbreviations](http://www.football-data.co.uk/notes.txt)
***
Since these columns are not in SQL naming convention will be more straightforward in later process. We will also analyse the column meaning

In [7]:
print(f'The list of E0_English Premier League 2019-2020 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

The list of E0_English Premier League 2019-2020 columns' names is: ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA']

In [9]:
# rename_cols(english_premier_league_df)
# rename_cols(efl_championship_df)
# rename_cols(efl_league_one_df)
# rename_cols(efl_league_two_df)

# print(f'The list of E0 English Premier League 2019-2020 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

# Drop unecessary columns

In [10]:
english_premier_league_df = english_premier_league_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_championship_df = efl_championship_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_league_one_df = efl_league_one_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
efl_league_two_df = efl_league_two_df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)

In [11]:
print(f'The list of E0 English Premier League 2019-2020 columns\' names is: {english_premier_league_df.columns.to_list()}\n\n\n')

The list of E0 English Premier League 2016 2017 columns' names is: ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA']

# Lower Case the content

In this section we will convert all the string value in the column to uppercase for further processing and keep all the string uniformly format. This will improve the analysis of the data, and also easier to perform any function related to the string.

In [12]:
# Cast all values inside the dataframe (except the columns' name) into upper case.
english_premier_league_df = english_premier_league_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_championship_df = efl_championship_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_league_one_df = efl_league_one_df.applymap(lambda s: s.lower() if type(s) == str else s)
efl_league_two_df = efl_league_two_df.applymap(lambda s: s.lower() if type(s) == str else s)

# Concat dataframes
Clear the existing index and reset it in the result by setting the ignore_index option to True.

In [13]:
df = pd.concat([english_premier_league_df, efl_championship_df, efl_league_one_df, efl_league_two_df], ignore_index=True)
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,e0,09/08/2019,20:00,liverpool,norwich,4,1,h,4,0,h,m oliver,15,12,7,5,9,9,11,2,0,2,0,0,1.14,10.00,19.00,1.14,8.25,18.50,1.15,8.00,18.00,1.15,9.59,18.05,1.12,8.5,21.00,1.14,9.5,23.00,1.16,10.00,23.00,1.14,8.75,19.83,1.40,3.00,1.40,3.11,1.45,3.11,1.41,2.92,-2.25,1.96,1.94,1.97,1.95,1.97,2.00,1.94,1.94,1.14,9.50,21.00,1.14,9.0,20.00,1.15,8.00,18.00,1.11,9.5,21.00,1.14,9.50,23.00,1.16,10.50,23.00,1.14,9.52,19.18,1.3,3.50,1.34,3.44,1.36,3.76,1.32,3.43,-2.25,1.91,1.99,1.94,1.98,1.99,2.07,1.90,1.99
1,e0,10/08/2019,12:30,west ham,man city,0,5,a,0,1,a,m dean,5,14,3,9,6,13,1,1,2,2,0,0,12.00,6.50,1.22,11.50,5.75,1.26,11.00,6.10,1.25,11.68,6.53,1.26,13.00,6.0,1.24,12.00,6.5,1.25,13.00,6.75,1.29,11.84,6.28,1.25,1.44,2.75,1.49,2.77,1.51,2.77,1.48,2.65,1.75,2.00,1.90,2.02,1.90,2.02,1.92,1.99,1.89,12.00,7.00,1.25,11.00,6.0,1.26,11.00,6.10,1.25,11.00,6.5,1.24,12.00,6.50,1.25,13.00,7.00,1.29,11.14,6.46,1.26,1.4,3.00,1.43,3.03,1.50,3.22,1.41,2.91,1.75,1.95,1.95,1.96,1.97,2.07,1.98,1.97,1.92
2,e0,10/08/2019,15:00,bournemouth,sheffield united,1,1,d,0,0,d,k friend,13,8,3,3,10,19,3,4,2,1,0,0,1.95,3.60,3.60,1.95,3.60,3.90,1.97,3.55,3.80,2.04,3.57,3.90,2.00,3.5,3.80,2.00,3.6,4.00,2.06,3.65,4.00,2.01,3.53,3.83,1.90,1.90,1.96,1.96,2.00,1.99,1.90,1.93,-0.50,2.01,1.89,2.04,1.88,2.04,1.91,2.00,1.88,1.95,3.70,4.20,1.95,3.6,3.90,1.97,3.55,3.85,1.95,3.6,3.90,2.00,3.60,4.00,2.03,3.70,4.20,1.98,3.58,3.96,1.9,1.90,1.94,1.97,1.97,1.98,1.91,1.92,-0.50,1.95,1.95,1.98,1.95,2.00,1.96,1.96,1.92
3,e0,10/08/2019,15:00,burnley,southampton,3,0,h,0,0,d,g scott,10,11,4,3,6,12,2,7,0,0,0,0,2.62,3.20,2.75,2.65,3.20,2.75,2.65,3.20,2.75,2.71,3.31,2.81,2.70,3.2,2.75,2.70,3.3,2.80,2.80,3.33,2.85,2.68,3.22,2.78,2.10,1.72,2.17,1.77,2.20,1.78,2.12,1.73,0.00,1.92,1.98,1.93,2.00,1.94,2.00,1.91,1.98,2.70,3.25,2.90,2.65,3.1,2.85,2.60,3.20,2.85,2.62,3.2,2.80,2.70,3.25,2.90,2.72,3.26,2.95,2.65,3.18,2.88,2.1,1.72,2.19,1.76,2.25,1.78,2.17,1.71,0.00,1.87,2.03,1.89,2.03,1.90,2.07,1.86,2.02
4,e0,10/08/2019,15:00,crystal palace,everton,0,0,d,0,0,d,j moss,6,10,2,3,16,14,6,2,2,1,0,1,3.00,3.25,2.37,3.20,3.20,2.35,3.10,3.20,2.40,3.21,3.37,2.39,3.10,3.3,2.35,3.20,3.3,2.45,3.21,3.40,2.52,3.13,3.27,2.40,2.20,1.66,2.23,1.74,2.25,1.74,2.18,1.70,0.25,1.85,2.05,1.88,2.05,1.88,2.09,1.84,2.04,3.40,3.50,2.25,3.30,3.3,2.25,3.40,3.30,2.20,3.30,3.3,2.25,3.40,3.30,2.25,3.55,3.50,2.34,3.41,3.37,2.23,2.2,1.66,2.22,1.74,2.28,1.77,2.17,1.71,0.25,1.82,2.08,1.97,1.96,2.03,2.08,1.96,1.93

# Data types

In [14]:
# convert columns to the best possible dtypes, object->string
df = df.convert_dtypes()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1772 entries, 0 to 1771
Columns: 103 entries, Div to AvgCAHA
dtypes: Float64(79), Int64(16), string(8)
memory usage: 1.6 MB

<a id="2.2.1"></a>
# Format date features

In [15]:
# Cast date columns to the Date data type
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1772 entries, 0 to 1771
Columns: 103 entries, Div to AvgCAHA
dtypes: Float64(79), Int64(16), datetime64[ns](1), string(7)
memory usage: 1.6 MB

# DROP NA & DUPLICATION

+ world_cup dataframe: year is the primary key

+ world_cup_match dataframe: year,match_id are the primary key

In [17]:
print("Number of rows before drop of duplicates in National Leagues:", len(df.index))
print("Number of duplicated records in National Leagues: ", df.duplicated().sum())
df = df.drop_duplicates(subset=['Div', 'Date', 'HomeTeam', 'AwayTeam'], keep="first")
print("Number of duplicated records AFTER DROP in National Leagues: ", df.duplicated().sum())
print("Number of rows after drop of duplicates in National Leagues:", len(df.index), "\n\n")

Number of rows before drop of duplicates in National Leagues: 1772
Number of duplicated records in National Leagues:  0
Number of duplicated records AFTER DROP in National Leagues:  0
Number of rows after drop of duplicates in National Leagues: 1772

In [18]:
print("The National Leagues dataframe BEFORE dropped has {} rows and {} columns".format(df.shape[0], df.shape[1]))
df = df.dropna(subset=['Div', 'Date', 'HomeTeam', 'AwayTeam'])
# display missing values in descending
print("The National Leagues dataframe AFTER dropped has {} rows and {} columns".format(df.shape[0], df.shape[1]),"\n\n\n")

The National Leagues dataframe BEFORE dropped has 1772 rows and 103 columns
The National Leagues dataframe AFTER dropped has 1772 rows and 103 columns

<a id="3"></a>
<h1 style="color:#ffc0cb;font-size:40px;font-family:Georgia;text-align:center;"><strong>3. Save the Intermediate data that has been transformed</strong></h1>

In [19]:
write_interim_path(df, '2019-2020.csv', 'national_leagues')

cleaned 2019-2020.csv data was successfully saved!